# Auto-generated by `flatc` from schemas/ui_snapshot.fbs
# Minimal example for demo—partial, real generated output will be longer!

import flatbuffers

class DOMSnapshot(object):
    # ... auto-generated API (truncated for brevity) ...
    @classmethod
    def CreateDOMSnapshot(cls, builder, url, html, timestamp, metadata):
        url_off = builder.CreateString(url)
        html_off = builder.CreateString(html)
        metadata_off = builder.CreateString(metadata)
        builder.StartObject(4)
        builder.PrependUOffsetTRelativeSlot(0, url_off, 0)
        builder.PrependUOffsetTRelativeSlot(1, html_off, 0)
        builder.PrependUint64Slot(2, timestamp, 0)
        builder.PrependUOffsetTRelativeSlot(3, metadata_off, 0)
        return builder.EndObject()