# relevant sections only show upgrade:
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: apps/web-app/.next

      - uses: actions/download-artifact@v4
        with:
          name: web-build
          path: .next